---
kind: workerConfig
version: udx.io/worker-v1/config
config:
  env:
    # Node environment
    NODE_ENV: ${NODE_ENV}
    PORT: ${PORT}
    NODE_PORT: ${NODE_PORT}
    
    # Service flags
    SERVICE_ENABLE_SSHD: ${SERVICE_ENABLE_SSHD}
    SERVICE_ENABLE_API: ${SERVICE_ENABLE_API}
    SERVICE_ENABLE_FIREBASE: ${SERVICE_ENABLE_FIREBASE}
    USE_GKE_GCLOUD_AUTH_PLUGIN: ${USE_GKE_GCLOUD_AUTH_PLUGIN}

    # Kubernetes configuration
    KUBERNETES_CLUSTER_ENDPOINT: ${KUBERNETES_CLUSTER_ENDPOINT}
    KUBERNETES_CLUSTER_NAME: ${KUBERNETES_CLUSTER_NAME}
    KUBERNETES_CLUSTER_NAMESPACE: ${KUBERNETES_CLUSTER_NAMESPACE}
    KUBERNETES_CLUSTER_USER_TOKEN: ${KUBERNETES_CLUSTER_USER_TOKEN}
    KUBERNETES_CLUSTER_SERVICEACCOUNT: ${KUBERNETES_CLUSTER_SERVICEACCOUNT}
    KUBERNETES_CLUSTER_CERTIFICATE: ${KUBERNETES_CLUSTER_CERTIFICATE}
    KUBERNETES_CLUSTER_USER_SECRET: ${KUBERNETES_CLUSTER_USER_SECRET}
    KUBERNETES_CLUSTER_CONTEXT: ${KUBERNETES_CLUSTER_CONTEXT}

    # GitHub configuration
    ACCESS_TOKEN: ${ACCESS_TOKEN}
    ALLOW_SSH_ACCESS_ROLES: ${ALLOW_SSH_ACCESS_ROLES}

  secrets:
    ACCESS_TOKEN: ${ACCESS_TOKEN}
    KUBERNETES_CLUSTER_USER_TOKEN: ${KUBERNETES_CLUSTER_USER_TOKEN}
    KUBERNETES_CLUSTER_USER_SECRET: ${KUBERNETES_CLUSTER_USER_SECRET}
